# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import objective_ai_pb2 as objective__ai__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in objective_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectiveAIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/objective_ai.ObjectiveAI/Query',
                request_serializer=objective__ai__pb2.QueryRequest.SerializeToString,
                response_deserializer=objective__ai__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.QueryStreaming = channel.unary_stream(
                '/objective_ai.ObjectiveAI/QueryStreaming',
                request_serializer=objective__ai__pb2.QueryRequest.SerializeToString,
                response_deserializer=objective__ai__pb2.QueryStreamingResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/objective_ai.ObjectiveAI/Chat',
                request_serializer=objective__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=objective__ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStreaming = channel.unary_stream(
                '/objective_ai.ObjectiveAI/ChatStreaming',
                request_serializer=objective__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=objective__ai__pb2.ChatStreamingResponse.FromString,
                _registered_method=True)


class ObjectiveAIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectiveAIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=objective__ai__pb2.QueryRequest.FromString,
                    response_serializer=objective__ai__pb2.QueryResponse.SerializeToString,
            ),
            'QueryStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryStreaming,
                    request_deserializer=objective__ai__pb2.QueryRequest.FromString,
                    response_serializer=objective__ai__pb2.QueryStreamingResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=objective__ai__pb2.ChatRequest.FromString,
                    response_serializer=objective__ai__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStreaming,
                    request_deserializer=objective__ai__pb2.ChatRequest.FromString,
                    response_serializer=objective__ai__pb2.ChatStreamingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objective_ai.ObjectiveAI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('objective_ai.ObjectiveAI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectiveAI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objective_ai.ObjectiveAI/Query',
            objective__ai__pb2.QueryRequest.SerializeToString,
            objective__ai__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/objective_ai.ObjectiveAI/QueryStreaming',
            objective__ai__pb2.QueryRequest.SerializeToString,
            objective__ai__pb2.QueryStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objective_ai.ObjectiveAI/Chat',
            objective__ai__pb2.ChatRequest.SerializeToString,
            objective__ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/objective_ai.ObjectiveAI/ChatStreaming',
            objective__ai__pb2.ChatRequest.SerializeToString,
            objective__ai__pb2.ChatStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
